import 'employee.dart';

void main() {
  List<Map<String, dynamic>> AllEmployee = [
    {
      'id': 1,
      'name': "Rohan",
      'gend': "male",
      'age': 22,
      'qual': "BA",
      'comp': "infinity",
      'role': "desginer",
      'exp': 3,
      'wage': 25000,
      'mono': "9876545738"
    },
    {
      'id': 2,
      'name': 'Jaya',
      'gend': 'female',
      'age': 30,
      'qual': 'MBA',
      'comp': 'TechCorp',
      'role': 'Project Manager',
      'exp': 8,
      'wage': 50000,
      'mono': '9876543210'
    },
    {
      'id': 3,
      'name': 'Jignesh',
      'gend': 'male',
      'age': 35,
      'qual': 'PhD',
      'comp': 'InnovateTech',
      'role': 'Research Scientist',
      'exp': 10,
      'wage': 80000,
      'mono': '9123456789'
    },
    {
      'id': 4,
      'name': 'Poonam',
      'gend': 'female',
      'age': 28,
      'qual': 'BSc',
      'comp': 'DigitalSolutions',
      'role': 'Software Engineer',
      'exp': 4,
      'wage': 40000,
      'mono': '8765432109'
    },
    {
      'id': 5,
      'name': 'Jagdish',
      'gend': 'male',
      'age': 25,
      'qual': 'BE',
      'comp': 'TechGenius',
      'role': 'Data Analyst',
      'exp': 2,
      'wage': 35000,
      'mono': '7890123456'
    },
    {
      'id': 6,
      'name': 'Kajal',
      'gend': 'female',
      'age': 27,
      'qual': 'MA',
      'comp': 'WebTech',
      'role': 'UX/UI Designer',
      'exp': 5,
      'wage': 45000,
      'mono': '7654321098'
    },
    {
      'id': 7,
      'name': 'Ketan',
      'gend': 'male',
      'age': 32,
      'qual': 'MSc',
      'comp': 'DataCo',
      'role': 'Data Scientist',
      'exp': 7,
      'wage': 60000,
      'mono': '6543210987'
    },
    {
      'id': 8,
      'name': 'Krishna',
      'gend': 'female',
      'age': 23,
      'qual': 'BA',
      'comp': 'InnoTech',
      'role': 'Frontend Developer',
      'exp': 1,
      'wage': 30000,
      'mono': '5432109876'
    },
    {
      'id': 9,
      'name': 'Krish',
      'gend': 'male',
      'age': 29,
      'qual': 'MBA',
      'comp': 'TechSolutions',
      'role': 'Product Manager',
      'exp': 6,
      'wage': 55000,
      'mono': '4321098765'
    },
    {
      'id': 10,
      'name': 'Bhavna',
      'gend': 'female',
      'age': 26,
      'qual': 'BSc',
      'comp': 'CodeCraft',
      'role': 'Full Stack Developer',
      'exp': 3,
      'wage': 38000,
      'mono': '3210987654'
    },
    {
      'id': 11,
      'name': 'Tarun',
      'gend': 'male',
      'age': 31,
      'qual': 'PhD',
      'comp': 'InnovateSoft',
      'role': 'Research Engineer',
      'exp': 9,
      'wage': 75000,
      'mono': '2109876543'
    },
    {
      'id': 12,
      'name': 'Roshni',
      'gend': 'female',
      'age': 24,
      'qual': 'BEng',
      'comp': 'TechSolutions',
      'role': 'Software Developer',
      'exp': 2,
      'wage': 35000,
      'mono': '1098765432'
    },
    {
      'id': 13,
      'name': 'Raghav',
      'gend': 'male',
      'age': 33,
      'qual': 'MS',
      'comp': 'DataTech',
      'role': 'Data Engineer',
      'exp': 7,
      'wage': 60000,
      'mono': '2087654321'
    },
    {
      'id': 14,
      'name': 'Mohini',
      'gend': 'female',
      'age': 29,
      'qual': 'MSc',
      'comp': 'InnovateSoft',
      'role': 'UX Designer',
      'exp': 5,
      'wage': 45000,
      'mono': '3076543210'
    },
    {
      'id': 15,
      'name': 'Mayur',
      'gend': 'male',
      'age': 27,
      'qual': 'BSc',
      'comp': 'CodeCraft',
      'role': 'Frontend Developer',
      'exp': 4,
      'wage': 40000,
      'mono': '4065432109'
    },
    {
      'id': 16,
      'name': 'Dipika',
      'gend': 'female',
      'age': 26,
      'qual': 'BE',
      'comp': 'TechGenius',
      'role': 'Product Manager',
      'exp': 3,
      'wage': 38000,
      'mono': '5054321098'
    },
    {
      'id': 17,
      'name': 'Keyur',
      'gend': 'male',
      'age': 31,
      'qual': 'PhD',
      'comp': 'InnovateTech',
      'role': 'Research Scientist',
      'exp': 8,
      'wage': 55000,
      'mono': '6043210987'
    },
    {
      'id': 18,
      'name': 'Priya',
      'gend': 'female',
      'age': 28,
      'qual': 'MA',
      'comp': 'WebTech',
      'role': 'Full Stack Developer',
      'exp': 5,
      'wage': 42000,
      'mono': '7032109876'
    },
    {
      'id': 19,
      'name': 'Dinesh',
      'gend': 'male',
      'age': 25,
      'qual': 'BSc',
      'comp': 'DigitalSolutions',
      'role': 'Data Analyst',
      'exp': 3,
      'wage': 35000,
      'mono': '8021098765'
    },
    {
      'id': 20,
      'name': 'Anjali',
      'gend': 'female',
      'age': 30,
      'qual': 'MBA',
      'comp': 'TechCorp',
      'role': 'Project Manager',
      'exp': 6,
      'wage': 52000,
      'mono': '9010987654'
    },
    {
      'id': 21,
      'name': 'Haresh',
      'gend': 'male',
      'age': 32,
      'qual': 'PhD',
      'comp': 'DataCo',
      'role': 'Data Scientist',
      'exp': 9,
      'wage': 70000,
      'mono': '0109876543'
    },
    {
      'id': 22,
      'name': 'Bhumika',
      'gend': 'female',
      'age': 27,
      'qual': 'BEng',
      'comp': 'TechSolutions',
      'role': 'Software Engineer',
      'exp': 3,
      'wage': 38000,
      'mono': '1098765432'
    },
    {
      'id': 23,
      'name': 'Akshay',
      'gend': 'male',
      'age': 34,
      'qual': 'MS',
      'comp': 'DataTech',
      'role': 'Data Analyst',
      'exp': 7,
      'wage': 60000,
      'mono': '2087654321'
    },
    {
      'id': 24,
      'name': 'Foram',
      'gend': 'female',
      'age': 25,
      'qual': 'MSc',
      'comp': 'InnovateSoft',
      'role': 'UX/UI Designer',
      'exp': 4,
      'wage': 42000,
      'mono': '3076543210'
    },
    {
      'id': 25,
      'name': 'Jignesh',
      'gend': 'male',
      'age': 28,
      'qual': 'BSc',
      'comp': 'CodeCraft',
      'role': 'Frontend Developer',
      'exp': 5,
      'wage': 40000,
      'mono': '4065432109'
    },
    {
      'id': 26,
      'name': 'Aarti',
      'gend': 'female',
      'age': 26,
      'qual': 'BE',
      'comp': 'TechGenius',
      'role': 'Product Manager',
      'exp': 4,
      'wage': 42000,
      'mono': '5054321098'
    },
    {
      'id': 27,
      'name': 'Suresh',
      'gend': 'male',
      'age': 30,
      'qual': 'PhD',
      'comp': 'InnovateTech',
      'role': 'Research Scientist',
      'exp': 8,
      'wage': 58000,
      'mono': '6043210987'
    },
    {
      'id': 28,
      'name': 'Jinal',
      'gend': 'female',
      'age': 29,
      'qual': 'MA',
      'comp': 'WebTech',
      'role': 'Full Stack Developer',
      'exp': 6,
      'wage': 45000,
      'mono': '7032109876'
    },
    {
      'id': 29,
      'name': 'Varun',
      'gend': 'male',
      'age': 26,
      'qual': 'BSc',
      'comp': 'DigitalSolutions',
      'role': 'Data Engineer',
      'exp': 4,
      'wage': 38000,
      'mono': '8021098765'
    },
    {
      'id': 30,
      'name': 'Alia',
      'gend': 'female',
      'age': 31,
      'qual': 'MBA',
      'comp': 'TechCorp',
      'role': 'Project Manager',
      'exp': 7,
      'wage': 55000,
      'mono': '9010987654'
    },
    {
      'id': 31,
      'name': 'Gopal',
      'gend': 'male',
      'age': 33,
      'qual': 'PhD',
      'comp': 'DataCo',
      'role': 'Data Scientist',
      'exp': 10,
      'wage': 75000,
      'mono': '0109876543'
    },
    {
      'id': 32,
      'name': 'Dhruvi',
      'gend': 'female',
      'age': 24,
      'qual': 'BEng',
      'comp': 'TechSolutions',
      'role': 'Software Developer',
      'exp': 2,
      'wage': 35000,
      'mono': '1098765432'
    },
    {
      'id': 33,
      'name': 'Mohit',
      'gend': 'male',
      'age': 33,
      'qual': 'MS',
      'comp': 'DataTech',
      'role': 'Data Analyst',
      'exp': 6,
      'wage': 58000,
      'mono': '2087654321'
    },
    {
      'id': 34,
      'name': 'Sanjna',
      'gend': 'female',
      'age': 26,
      'qual': 'MSc',
      'comp': 'InnovateSoft',
      'role': 'UX Designer',
      'exp': 4,
      'wage': 42000,
      'mono': '3076543210'
    },
    {
      'id': 35,
      'name': 'Sanjay',
      'gend': 'male',
      'age': 27,
      'qual': 'BSc',
      'comp': 'CodeCraft',
      'role': 'Frontend Developer',
      'exp': 3,
      'wage': 38000,
      'mono': '4065432109'
    },
    {
      'id': 36,
      'name': 'Ruhi',
      'gend': 'female',
      'age': 25,
      'qual': 'BE',
      'comp': 'TechGenius',
      'role': 'Product Manager',
      'exp': 2,
      'wage': 35000,
      'mono': '5054321098'
    },
    {
      'id': 37,
      'name': 'Rakesh',
      'gend': 'male',
      'age': 31,
      'qual': 'PhD',
      'comp': 'InnovateTech',
      'role': 'Research Scientist',
      'exp': 7,
      'wage': 60000,
      'mono': '6043210987'
    },
    {
      'id': 38,
      'name': 'Kinjal',
      'gend': 'female',
      'age': 28,
      'qual': 'MA',
      'comp': 'WebTech',
      'role': 'Full Stack Developer',
      'exp': 5,
      'wage': 45000,
      'mono': '7032109876'
    },
    {
      'id': 39,
      'name': 'Naresh',
      'gend': 'male',
      'age': 29,
      'qual': 'BSc',
      'comp': 'DigitalSolutions',
      'role': 'Data Engineer',
      'exp': 4,
      'wage': 40000,
      'mono': '8021098765'
    },
    {
      'id': 40,
      'name': 'Rekha',
      'gend': 'female',
      'age': 30,
      'qual': 'MBA',
      'comp': 'TechCorp',
      'role': 'Project Manager',
      'exp': 6,
      'wage': 55000,
      'mono': '9010987654'
    },
    {
      'id': 41,
      'name': 'Lakhan',
      'gend': 'male',
      'age': 32,
      'qual': 'PhD',
      'comp': 'DataCo',
      'role': 'Data Scientist',
      'exp': 8,
      'wage': 65000,
      'mono': '0109876543'
    },
    {
      'id': 42,
      'name': 'Lila',
      'gend': 'female',
      'age': 27,
      'qual': 'BEng',
      'comp': 'TechSolutions',
      'role': 'Software Engineer',
      'exp': 3,
      'wage': 38000,
      'mono': '1098765432'
    },
    {
      'id': 43,
      'name': 'Mahesh',
      'gend': 'male',
      'age': 34,
      'qual': 'MS',
      'comp': 'DataTech',
      'role': 'Data Analyst',
      'exp': 7,
      'wage': 60000,
      'mono': '2087654321'
    },
    {
      'id': 44,
      'name': 'Mina',
      'gend': 'female',
      'age': 28,
      'qual': 'MSc',
      'comp': 'InnovateSoft',
      'role': 'UX/UI Designer',
      'exp': 5,
      'wage': 42000,
      'mono': '3076543210'
    },
    {
      'id': 45,
      'name': 'Parekh',
      'gend': 'male',
      'age': 26,
      'qual': 'BSc',
      'comp': 'CodeCraft',
      'role': 'Frontend Developer',
      'exp': 4,
      'wage': 40000,
      'mono': '4065432109'
    },
    {
      'id': 46,
      'name': 'Heena',
      'gend': 'female',
      'age': 25,
      'qual': 'BE',
      'comp': 'TechGenius',
      'role': 'Product Manager',
      'exp': 3,
      'wage': 35000,
      'mono': '5054321098'
    },
    {
      'id': 47,
      'name': 'Chintan',
      'gend': 'male',
      'age': 31,
      'qual': 'PhD',
      'comp': 'InnovateTech',
      'role': 'Research Scientist',
      'exp': 8,
      'wage': 60000,
      'mono': '6043210987'
    },
    {
      'id': 48,
      'name': 'Gopi',
      'gend': 'female',
      'age': 29,
      'qual': 'MA',
      'comp': 'WebTech',
      'role': 'Full Stack Developer',
      'exp': 6,
      'wage': 45000,
      'mono': '7032109876'
    },
    {
      'id': 49,
      'name': 'Sagar',
      'gend': 'male',
      'age': 30,
      'qual': 'BSc',
      'comp': 'DigitalSolutions',
      'role': 'Data Engineer',
      'exp': 4,
      'wage': 38000,
      'mono': '8021098765'
    },
    {
      'id': 50,
      'name': 'Sangita',
      'gend': 'female',
      'age': 33,
      'qual': 'MBA',
      'comp': 'TechCorp',
      'role': 'Project Manager',
      'exp': 7,
      'wage': 55000,
      'mono': '9010987654'
    }
  ];

  List<employee> E1 = AllEmployee.map((e) => employee.data(Data: e)).toList();

  E1.forEach((element) {
    element.getData();
  });
}
